name: Build Android APK
on:
  push:
    branches: [ main ] # Se déclenche quand tu envoies du code sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: npm install

      # Cette étape recrée ton fichier .env à partir des secrets GitHub
      - name: Create .env file
        run: |
          echo "VITE_API_KEY=${{ secrets.MY_API_KEY }}" > .env
          echo "VITE_OTHER_VAR=${{ secrets.OTHER_VAR }}" >> .env

      - name: Build Web Project
        run: npm run build

      - name: Install Capacitor & Build Android
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init JIII com.jiii.app --web-dir dist
          npx cap add android
          npx cap sync android
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: JIII-Mobile-App
          path: android/app/build/outputs/apk/debug/app-debug.apk